### ISSUE TITLE
Unable to register plugin on Elastic 2.3.3 (Cloudwatt Swift)

### ISSUE THREAD

**Issue by Freds72AtWork** [wikimedia/search-repository-swift#21] opened 2016-06-13 08:22 UTC
Using this registration command:
```
curl -XPUT 'http://192.168.0.10:9200/_snapshot/swift_backup' -d '{ "type": "swift", "settings": {
    "swift_url": "https://identity.fr1.cloudwatt.com:443/v2.0",
    "swift_container": "es_backup",
    "swift_authmethod" : "KEYSTONE",
    "swift_username": "my_mail@mycompany.com",
    "swift_password": "*********************",
    "swift_tenantname" : "my_tenant" 
    }
}'
```
I got this suppressAccessChecks error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "repository_exception",
                "reason": "[swift_backup] failed to create repository"
            }
        ],
        "type": "repository_exception",
        "reason": "[swift_backup] failed to create repository",
        "caused_by": {
            "type": "creation_exception",
            "reason": "Guice creation errors:\n\n1) Error injecting constructor, ElasticsearchException[Unable to authenticate to Swift Keystone https://identity.fr1.cloudwatt.com:443/v2.0/my_mail@mycompany.com/*******************/my_tenant]; nested: CommandException[Unable to set the JSON body for the authentication header]; nested: JsonMappingException[Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")];\n  at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)\n  while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error",
            "caused_by": {
                "type": "exception",
                "reason": "Unable to authenticate to Swift Keystone https://identity.fr1.cloudwatt.com:443/v2.0/my_mail@mycompany.com/*******************/my_tenant",
                "caused_by": {
                    "type": "command_exception",
                    "reason": "Unable to set the JSON body for the authentication header",
                    "caused_by": {
                        "type": "json_mapping_exception",
                        "reason": "Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")",
                        "caused_by": {
                            "type": "illegal_argument_exception",
                            "reason": "Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied (\"java.lang.reflect.ReflectPermission\" \"suppressAccessChecks\")"
                        }
                    }
                }
            }
        }
    },
    "status": 500
}
```

**Comment by Freds72AtWork** [comment] 2016-06-14 07:35
FYI, got it working by recompiling the pluging following Elastic [guidelines on plugin security](https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html), e.g.:
- added a plugin-security.policy file
```
grant {
  permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
};
```
- wrapped account creation call into a priviliged section:
```java
        SecurityManager sm = System.getSecurityManager();
        if (sm != null) {
          // unprivileged code such as scripts do not have SpecialPermission
          sm.checkPermission(new SpecialPermission());
        }
        Account account = 
	        AccessController.doPrivileged(
	        		new PrivilegedAction<Account>() {
	                    public Account run() {
	                    	return SwiftAccountFactory.createAccount(swiftService, url, username, password, tenantName, authMethod);
	                    }
	        		});
```

I now get the complementary warning and was able to successfuly create the repository.

**Comment by nomoa** [comment] 2016-06-14 10:09
Thanks for the report, yes this problem is related to the security manager however I think we can fix joss to make it more friendly in secure environment.
Would you mind to do a test with this version : https://drive.google.com/file/d/0Bzo2vOqfrXhJMUJZN2o4WVhkVUE/view?usp=sharing

If it works I'll submit a PR to joss.

Thanks!

**Comment by Freds72AtWork** [comment] 2016-06-14 11:08
Same access error (using ES 2.3.3 on Windows):

[2016-06-14 11:49:32,889][WARN ][repositories             ] [Autolycus] failed to create repository [swift][swift_backup_v2]
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, ElasticsearchException[Unable to authenticate to Swift Keystone https://identity.fr1.cloudwatt.com:443/v2.0/tokens/my_mail@company.com/*****************/my_tenant]; nested: CommandException[Unable to set the JSON body for the authentication header]; nested: JsonMappingException[Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
  at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(Unknown Source)
  while locating org.wikimedia.elasticsearch.swift.repositories.SwiftRepository
  while locating org.elasticsearch.repositories.Repository

1 error
                at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:360)
                at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
                at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
                at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:157)
                at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
                at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
                at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
                at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
                at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
                at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
                at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
                at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)
Caused by: ElasticsearchException[Unable to authenticate to Swift Keystone https://identity.fr1.cloudwatt.com:443/v2.0/tokens/my_mail@company.com/*****************/my_tenant]; nested: CommandException[Unable to set the JSON body for the authentication header]; nested: JsonMappingException[Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")]; nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.identity.authentication.PasswordCredentials org.javaswift.joss.command.shared.identity.authentication.Authentication.getPasswordCredentials() (from class org.javaswift.joss.command.shared.identity.authentication.Authentication; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
                at org.wikimedia.elasticsearch.swift.repositories.SwiftService.swiftKeyStone(SwiftService.java:63)
                at org.wikimedia.elasticsearch.swift.repositories.SwiftAccountFactory.createAccount(SwiftAccountFactory.java:9)
                at org.wikimedia.elasticsearch.swift.repositories.SwiftRepository.<init>(SwiftRepository.java:65)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
                at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
                at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
                at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
                at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
                at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
                at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
                at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
                at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
                at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
                at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
                at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
                at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
                at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)

**Comment by Freds72AtWork** [comment] 2016-06-14 11:09
Aren't you missing the security policy file?
You need to add it to the plugin.xml file to make it part of the package.

**Comment by nomoa** [comment] 2016-06-14 11:22
Thanks for testing!

PasswordCredentials lacks an empty constructor and I guess it's the cause...

Basically I'd like to make this plugin works out of the box without any special permissions.

I don't know what to do here:
- Fix joss to make it SecureManager friendly
- Wrap all joss methods with a PrivilegedAction

PrivilegedAction will add a lot of boiler plate code to this plugin it's why I'd prefer to fix joss but I'm not sure yet if it's possible.

**Comment by Freds72AtWork** [comment] 2016-06-14 11:48
I tried that route (see attached code) – it works for registration but can't get it to work when getting details on a repository:

http://127.0.0.1:9200/_snapshot/swift_backup_v2/_all

IndexShardSnapshotFailedException[Unable to execute the HTTP call or to convert the HTTP Response];
nested: CommandException[Unable to execute the HTTP call or to convert the HTTP Response];
nested: JsonMappingException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];
nested: IllegalArgumentException[Can not access public org.javaswift.joss.command.shared.container.StoredObjectListElement() (from class org.javaswift.joss.command.shared.container.StoredObjectListElement; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")];

That said, I am not Java expert (and must admit that I don't get why reflection is used within the context of this project…).

Frederic

**Comment by nomoa** [comment] 2016-06-14 13:37
I uploaded a new version: https://drive.google.com/file/d/0Bzo2vOqfrXhJN21WUnBWVUFpSFk/view?usp=sharing

This time I wrapped all swift access with a PrivilegedAction.

If you have time to give it a try it'd be much appreciated.

Thanks!

**Comment by Freds72AtWork** [comment] 2016-06-14 14:24
Registration is now working but the _all method still fails (e.g. StoredObjectListElement()).

**Comment by nomoa** [comment] 2016-06-14 16:06
It works for me now, do you have the full stack from elasticsearch logs?

**Comment by Freds72AtWork** [comment] 2016-06-14 16:53
This is indeed working – I was using an old repository with non-existing indices on my test Elastic instance :[
Waiting for an official release now!

**Comment by nomoa** [comment] 2016-06-14 17:11
Awesome thanks!

**Comment by Freds72AtWork** [comment] 2016-06-15 09:34
FYI, I was able to backup a 4-node ES 2.3.3 (CentOS 7 / JDK 8) with the "patch" version (2.3.3.1).

**Comment by nomoa** [comment] 2016-06-15 09:36
Patch is currently in review: https://gerrit.wikimedia.org/r/#/c/294345/
As soon as it is merged I'll release a fix.

**Comment by aabed** [comment] 2016-06-25 18:46
I believe I am facing the same problem with rackspace 
When will the review be done :)

**Closed** 2016-06-27 12:47 UTC
